name: Build and test

on:
  push:
    branches:
      - '*'

jobs:
  deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install dependencies
        run: npm install
      - name: Check style with lint
        run: npm run eslint
      - name: production build
        run: npm run build
      - name: Acquire browser for playwright
        run: npx playwright install 
      - name: Run Playwright tests
        run: npm run test

  version_control:
    needs: [deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.70.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch